version: "3"
services:
  apiserver:
    container_name: asyncapi
    image: mchiu2006/asyncapi
    build:
      context: .
      dockerfile: ./Dockerfile
      target: asyncapi
    ports:
      - 80:80
    depends_on:
      - redis
      - db
  redis:
    container_name: redis
    image: redis
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=asyncapi_db
